{
	"version": 1558425333,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bg1-sheet0.png",
		"images/slid1.png",
		"images/butonmanu1-sheet0.png",
		"images/btmanu2-sheet0.png",
		"images/btmanu3-sheet0.png",
		"images/btmanu4-sheet0.png",
		"images/exit-sheet0.png",
		"images/aboutbut-sheet0.png",
		"images/bg2-sheet0.png",
		"images/bggame-sheet0.png",
		"images/targetgame-sheet0.png",
		"images/keepergmae-sheet0.png",
		"images/ballgame-sheet0.png",
		"images/bggame2-sheet0.png",
		"images/sprite-sheet0.png",
		"images/lette-sheet0.png",
		"images/lette-sheet1.png",
		"images/lette-sheet2.png",
		"images/drop1-sheet0.png",
		"images/book1-sheet0.png",
		"images/particles.png",
		"images/btnext-sheet0.png",
		"images/bgtest-sheet0.png",
		"images/bgtext-sheet0.png",
		"images/testc1-sheet0.png",
		"images/testc2-sheet0.png",
		"images/testc3-sheet0.png",
		"images/testc4-sheet0.png",
		"images/bgevoluation-sheet0.png",
		"images/bgtohome-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/scrollpage-sheet0.png",
		"images/bggamehub-sheet0.png",
		"images/gogame1-sheet0.png",
		"images/gogame2-sheet0.png",
		"images/bgvideo-sheet0.png",
		"images/bgaboutme-sheet0.png",
		"images/bglogin-sheet0.png",
		"images/poppup-sheet0.png",
		"images/btlogin-sheet0.png",
		"images/bgwellcome-sheet0.png",
		"images/btlogout-sheet0.png",
		"images/title-sheet0.png",
		"images/spritefont2.png",
		"images/btplay-sheet0.png",
		"images/btpaus-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/bgt2-sheet0.png",
		"images/bgt3-sheet0.png",
		"images/bgt4-sheet0.png",
		"images/bgt5-sheet0.png",
		"images/bgt6-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/gotoweb-sheet0.png",
		"media/กระดิ่ง 4 (online-audio-converter.com).ogg",
		"media/กระดิ่ง 4.ogg",
		"media/ตบมือ 1.ogg",
		"media/ตบมือ 2.ogg",
		"media/ตลก 8.ogg",
		"media/นก 1.ogg",
		"media/นก 2.ogg",
		"media/นก 3.ogg",
		"media/start.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"vooo.webm"
	]
}